config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#index'

  get '/logout' => 'sessions#logout', as: :logout
  get '/signin' => 'sessions#signin', as: :signin
  post '/signin' => 'sessions#create'

  get '/activation_result' => 'static_pages#activation_result', as: :activation_result
  get '/after-signup' => 'static_pages#after_signup', as: :after_signup

  get '/member/profile' => 'member#show', as: :member_profile
  get '/member/:type' => 'member#new', as: :new_member
  post '/member' => 'member#create'
  post '/member/change-profile-pic' => 'member#change_profile_pic'

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
    if logged_in?
      redirect_to member_profile_path
    end
  end

  def activation_result
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/activation_result.html.erb
<% provide(:title, 'Activation') %>

<div class="container">
  <div class="row">
    <% if flash[:success] %>
        <div class="alert alert-success"><%= flash[:success] %> &nbsp;<%= link_to 'Sign-in', signin_path %></div>
    <% elsif flash[:danger] %>
        <div class="alert alert-danger"><%= flash[:danger] %></div>
    <% else %>
        <script type="text/javascript">
            window.location.href="/"
        </script>
    <% end %>
  </div>
</div>

app/views/static_pages/after_signup.html.erb
<% provide(:title, 'Sign-up') %>
<div class="container">
  <div class="row">
    <% if flash[:success] %>
        <div class="alert alert-success">Sign-up successful. An email is sent to you to activate your account before you can sign-in</div>
    <% else %>
        <script type="text/javascript">
            window.location.href="/signin"
        </script>
    <% end %>
  </div>
</div>

app/views/static_pages/index.html.erb
<% provide(:title, 'Home') %>

<header class="hero text-center">
  <div class="container">

    <div class="hero--info">
      <div class="hero-header">
        <h1 class="hero--info__header">Skowars is All You Need</h1>
        <p class="lead">Need a sponsor for your education?</p>
      </div>

      <ul class="list-inline">
        <li><%= link_to 'I want to sponsor', new_member_path(:type => "sponsor"), class: "btn" %></li>
        <li><%= link_to 'I want to be a skowar', new_member_path(:type => "skowar"), class: "btn btn-secondary" %></li>
      </ul>
    </div>
  </div>
</header>