config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#index'

  get '/logout' => 'sessions#logout', as: :logout
  get '/signin' => 'sessions#signin', as: :signin
  post '/signin' => 'sessions#create'

  get '/activation_result' => 'static_pages#activation_result', as: :activation_result
  get '/after-signup' => 'static_pages#after_signup', as: :after_signup

  get '/member/profile' => 'member#show', as: :member_profile
  get '/member/:type' => 'member#new', as: :new_member
  post '/member' => 'member#create'
  post '/member/change-profile-pic' => 'member#change_profile_pic'

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title><%= yield (:title) %> | Skowars</title>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= favicon_link_tag 'favicon.png' %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="page-container">


  <!-- Navigation -->
  <nav class="navbar">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">skowars</a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
          <li class="active"><a href="/">Home</a></li>
          <li><a href="#profile">Profile</a></li>
          <li><a href="#find">Find Skowars</a></li>
          <li><a href="#messages">Messages</a></li>
          <li><a href="#notif">Notifications</a></li>
          <% if logged_in? %>
            <li><%= link_to 'Log out', logout_path, class: "btn-link" %></li>
          <% else %>
             <li><%= link_to 'Sign-in', signin_path,  class: "btn-link" %></li>
          <% end %>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </nav>

  <% if flash[:info] %>
      <div class="container">
        <div class="alert alert-info"><%= flash[:info] %></div>
      </div>
  <%end %>
  <%= yield %>
</div> <!--/ #main-wrapper -->

<footer>
  <div class="footer">
    <div class="container">
    </div>
  </div>

  <div class="credits text-center">
    <p>Made with <i class="fa fa-heart"></i> from Cebu, Philippines.</p>
  </div>

  <!-- Modal -->
  <div class="modal fade" id="image-viewer-modal" tabindex="-1" role="dialog" aria-labelledby="image-viewer-label">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        </div>
        <div class="modal-body">
        </div>
      </div>
    </div>
  </div>

</footer>

</body>
</html>